### ISSUE TITLE
Docker image name in README.md is incorrect

### ISSUE THREAD

**Issue by Sudarshan-21** [openzim/kolibri#103]
System description:
OS: Linux Mint 21.3 Cinnamon
Browser: Chrome(latest v)

while running the project using docker, I am getting following error, am I missing any step?

![Screenshot from 2024-03-06 19-01-02](https://github.com/openzim/kolibri/assets/137636943/3493cc24-2c9b-4aa8-ab4c-7dbbe4126e33)

**Comment by benoit74** [comment]
Image is named `kolibri`, not `kolibri2zim`: https://github.com/openzim/kolibri/pkgs/container/kolibri

**Comment by benoit74** [comment]
Oh, the README is incorrect.

**Comment by benoit74** [comment]
README fixed, sorry about that
