### ISSUE TITLE
Issue with type checking in Vue when using JSX.

### ISSUE THREAD

**Issue by Sudarshan-21** [openzim/kolibri#122]
![Screenshot from 2024-04-02 20-36-01](https://github.com/openzim/kolibri/assets/137636943/1409e6ae-88d4-4e77-85c7-cda81f7077e9)

I am not sure if we need this issue here or not, but I would like to know if we need the mentioned `@vue/runtime-dom` in the project.

**Comment by benoit74** [comment]
I don't get it. We are using Vue 3 and your screenshot complains about Vue 2. Could you please dig a bit and explain why we need `@vue/runtime-dom` in the project?

**Comment by Sudarshan-21** [comment]
I realized that the error with Vue 2 was arising due to the version conflicts of the Vue on my local machine and the one used in the project.

But I found something else too.
ts was not able to recognize image files as modules. So it was showing error while importing images. Creating an issue on this here #124 .
