### ISSUE TITLE
African Storybooks

### ISSUE THREAD

**Issue by Popolechien** [openzim/kolibri#13]
- Website URL: https://africanstorybook.org/
- License: CC-by (sometimes -NC)
- Desired ZIM Title: African Storybooks
- Desired ZIM Description: Picture storybooks for children’s literacy, enjoyment and imagination

The books are allegedly available in several dozen languages, so it would be nice to have a separate zim for each. [Storybooks Canada](https://storybookscanada.ca/) has 40 of these already sorted in a few languages and a [git repo](https://github.com/global-asp/) (with this list [here](https://global-asp.github.io/stories/) that might be an easier starting point (Source descriptions [here](https://storybookscanada.ca/about/source/)). Likewise [Global Storybooks](https://globalstorybooks.net/) (same books but sorted by country instead of languages, which is kind of odd as two countries might share a language and therefore display the exact same content).

**Comment by benoit74** [comment]
I just ran a test with channel ID "f9d3e0e46ea25789bbed672ff6a399ed" and `kolibri2zim` scrapper.
This is working like a charm.
Who should we assign to create the recipe on zimfarm? Should we create an issue in `zim-requests` and close this one?

**Comment by rgaudin** [comment]
You can create a zim-request ticket with the tech details (scraper, channel, etc) and let them handle it. Mention this ticket.

**Comment by Popolechien** [comment]
@benoit74 please assign @RavanJAltaie to the task
