### ISSUE TITLE
Missing favicon on ZIM

### ISSUE THREAD

**Issue by rgaudin** [openzim/kolibri#29]
This is a pylibzim related issue but the root cause hasn't been identified yet (and it depends on usage). favicon is added and the favicon_entry is set but kiwixlib's meta can't find it

**Comment by rgaudin** [comment]
https://github.com/openzim/libzim/issues/525

**Comment by benoit74** [comment]
This has been fixed upstream and is now ok with recent zimscraperlib / libzim.
