### ISSUE TITLE
Better UI: fix carousel and its arrows

### ISSUE THREAD

**Issue by benoit74** [openzim/kolibri#71]
Things to fix:
- arrows are very ugly on big screens where they float wide away on screen borders
- carousel is infinite, which makes little sens
- carousel is displayed even when there is less than 4 items (arrows should be hidden at least)
- arrows icons are based on inline SVG ; we must use a font-awesome icon or something like that

![image](https://github.com/openzim/kolibri/assets/7102089/2a284ead-729e-4f97-beea-d227002fbcce)

**Comment by psankhe28** [comment]
Hello @benoit74, I'm interested in contributing to the project. I've successfully set up the new_ui branch and folder named zimui. However, when I run the project, I encounter a blank screen. Can you assist with this issue?

**Comment by benoit74** [comment]
Hello, you are probably missing JSON files that will be present inside the ZIM file but are only generated at scraper run time.

You will find more details [here](https://github.com/openzim/kolibri/blob/new_ui/CONTRIBUTING.md#developing-the-zim-ui-in-vuejs) about how to "hack" the thing so that you have these files available locally for development.

Do not hesitate to modify the generated JSON files to have sufficient data to display and exercise the expected behaviors (lots of items, less than 4 items, ...).

I've assigned the issue to you, please keep us informed of your progress (even slow, we do not mind) or struggles (it is normal to have some). Without news from you after some weeks, I will have to reassign the issue, assuming you are not making any progress.

Nota: I also added a screenshot to the first comment to ensure we are all speaking about the same things.

**Comment by psankhe28** [comment]
Thank you, @benoit74. I will follow the steps and update you on the progress regarding the issue as well.

**Comment by psankhe28** [comment]
Hi @benoit74 , I am getting the following error on running the command: docker build -t local-kolibri2zim .

![image](https://github.com/openzim/kolibri/assets/84843461/71b5c371-60e3-4a8a-b9ce-b8c6a8e27628)

**Comment by benoit74** [comment]
Could you please confirm which command you were running?

This looks like a Debian issue while building the Docker image. Did you tried again to run the recipe after some time? (the log suggest to wait 30 mins)

I don't know exactly what you are doing but this looks like a local developer setup issue where we unfortunately won't be able to help a lot. I ran `docker build .` in the `new_ui` branch just right now and it worked well.

Btw, I just merged into `new_ui` all recent changes which happened on `main` branch. You should update your local copy to get these changes, some of them are mandatory to have proper Python/hatch operation.

**Comment by psankhe28** [comment]
Command: docker build -t local-kolibri2zim .
I was trying it in Windows on git bash.

**Comment by benoit74** [comment]
Unfortunately, it works on my machine, and it works in Github CI I just launched on `new_ui` branch [here](https://github.com/openzim/kolibri/actions/runs/7992982869?pr=90) ... so definitely something linked to your local setup

**Comment by psankhe28** [comment]
I tried again but I guess it might be the issue with my system.

**Comment by githyuvi** [comment]
@benoit74  I have addressed all other issues. 
But when I use font awesome icons. When I click on the left or right icon both default and fa icon is getting displayed during transition of slides . But when transition is over , only fa icon is visible which is what we need .

Should I keep the default icon ?
Please assign this issue to me

**Comment by benoit74** [comment]
I'm not sure to fully understand what the default icon is, but if I get it right, I don't think we want to keep the default icon at all. It should always be left or right icons, nothing else.

Propose a PR with what makes the more sense to you, and we can discuss this kind of details over there (target branch of the PR must be `new_ui`, we are not yet ready to merge into `main` branch)

**Comment by githyuvi** [comment]
@benoit74 Please review the changes

**Comment by githyuvi** [comment]
@benoit74 All 4 things will be fixed. 

Additional Suggestion - Have you given a thought to using TailwindCSS with Vue3 instead of Bootstrap. Bootstrap provided very less flexibility and premade components are very difficult to customize.

**Comment by benoit74** [comment]
> Have you given a thought to using TailwindCSS with Vue3 instead of Bootstrap. Bootstrap provides very less flexibility and premade components are very difficult to customize.

This is still an open question on our end. I just created https://github.com/openzim/overview/issues/30 to address the question and your opinion is welcomed on this issue (and it could be an important part of your GSoC proposal).

**Comment by benoit74** [comment]
Work completed with #98 / #99
