### ISSUE TITLE
Better UI : fix bottom of the page issue

### ISSUE THREAD

**Issue by benoit74** [openzim/kolibri#72]
With new UI, in AfricanStoryBook, frequently (not systematically), when I browse one language and come back, I find myself at the bottom of the page (seeing Yoruba), while I left homepage on top of the page. This is disturbing.

**Comment by githyuvi** [comment]
@benoit74  As the docker zim building process is very time consuming. I need to clarify few things before working on this.
1. I need to create AfricanStoryBook zim using its 32bit channel id from this link https://studio.learningequality.org/en/channels/f9d3e0e46ea25789bbed672ff6a399ed/#/b01f7684d24c44c0845eaae166d5bba3
2. Correct me if I am wrong, right now we can work with only one zim at a time as we need to clear zimui/public folder before creating a new zim. So how can we work with multiple zim files. For now keeping a copy of previous zims public folder looks like an only solution. 
3.  Is there any other way we can explore to make this development process faster.

**Comment by benoit74** [comment]
And note that while this issue has been reported on AfricanStoryBook, I'm quite sure it impacts all our Kolibri ZIMs

**Comment by githyuvi** [comment]
Thanks for the clarification.
