### ISSUE TITLE
`Name` metadata is incorrect

### ISSUE THREAD

**Issue by rgaudin** [openzim/kolibri#76]
`Name` metadata contains the filename.

See https://library.kiwix.org/raw/africanstorybook.org_mul_all_2024-01/meta/Name and https://farm.openzim.org/pipeline/56c9204d-0788-4773-9641-0df95bd14850/debug

**Comment by benoit74** [comment]
To be clear for the ones who might be interested in solving this: the `Name` metadata should contain the `--name` CLI argument.
