### ISSUE TITLE
Is there an issue with video caching?

### ISSUE THREAD

**Issue by benoit74** [openzim/kolibri#82]
The last runs of khanacademy seems to be re-encoding a lot of videos.

See for instance https://farm.openzim.org/recipes/khanacademy-fr-kolibri

While it was understandable for https://farm.openzim.org/pipeline/c06a8148-7d9a-422c-b5b4-abfe93d51168 since it was the first execution since 10 months and we could imagine some videos had changed, it is way less understandable for https://farm.openzim.org/pipeline/7968d23c-e404-4d8f-b079-2664ad94299b

https://farm.openzim.org/recipes/khanacademy-en-kolibri seems to be suffering from the same issue.

**Comment by benoit74** [comment]
S3 bucket used in production is empty, so YES, there is a video caching issue.

It looks like [this callback](https://github.com/openzim/kolibri/blob/8d64526cb0beb911455cce382c3c8d8385d7ec3d/src/kolibri2zim/scraper.py#L474) (supposed to be called once the item has been added to the ZIM but before the removal of the file from the filesystem) is never called.

@rgaudin is it done properly or did the libzim API changed?

**Comment by rgaudin** [comment]
I don't remember any change regarding this. It's mostly in scraperlib I think

**Comment by rgaudin** [comment]
But given the bucket is empty, it never worked obviously

**Comment by benoit74** [comment]
OK, I will have a look into it (even if I still think we should get rid of it since it is not necessary and also mentioned in the codebase that their usage might be an issue: https://github.com/openzim/kolibri/blob/8d64526cb0beb911455cce382c3c8d8385d7ec3d/src/kolibri2zim/scraper.py#L859)

**Comment by kelson42** [comment]
Any think can be done in scraperlib to mutualize/check that this part works fine. It's worrying to see that kind of bug on scrapers.

**Comment by rgaudin** [comment]
> @benoit74 Anything can be done in scraperlib to mutualize/check that this part (download/optimisation/caching) of videos works fine in scrapers? It's worrying to see that kind of bug on scrapers.

It's already using shared primitives. The bug is that the arguments are passed to the wrong object. It's a typo.

Typo happen, the main problem is it went unnoticed for this long:

- we didn't check the bucket after initial run.
- we didn't look at zimfarm to see that we had no time gain after first successful run

That's because a worker's admin noticed the load that we found out we were encoding videos

**Comment by benoit74** [comment]
There are many things which could / should be checked on every scrapers. 

As said by @rgaudin, very basic principles have not been respected here, it is not like we are beginning to see situations where something was was working and suddenly stops. So I would not put a high priority on implemented automated checks. I nevertheless opened an issue with a proposition: https://github.com/openzim/python-scraperlib/issues/124
