### ISSUE TITLE
Code Refactoring: "CONTRIBUTING.md" file fix

### ISSUE THREAD

**Issue by Pagla-Dasu** [openzim/kolibri#91]
"Extract interesting ZIM content and move it to the `public` folder." :

The bash commands in this part of the `Contributing.md` file have some typos and missing elements and need refactoring for a smooth experience for the next contributor.

Assign me this issue, @benoit74 , and I will look into it.

**Comment by benoit74** [comment]
Thank you! I suppose you are referring to the current content of the `new_ui` branch, am I correct?

**Comment by Pagla-Dasu** [comment]
Yes, for the `new_ui` branch.

**Comment by Pagla-Dasu** [comment]
@benoit74 , do I need to crate a new tag version for this change too or should I just push it to the previous tagged version?

**Comment by benoit74** [comment]
you must not push to tags
you must push to a branch of your own (choose a meaningful name) and create a PR.
See https://github.com/openzim/overview/wiki/openZIM-code-contribution-workflow

**Comment by Pagla-Dasu** [comment]
@benoit74 , [PR](https://github.com/openzim/kolibri/pull/92) , check this out and do review.

**Comment by Pagla-Dasu** [comment]
Issue Solved, Closing the issue.
